### PR TITLE
Add visual card editor support 

### LINKED ISSUE #146: Errors while using the visual card editor
Not sure if this is new or not... 

stack

### LINKED ISSUE #151: Custom element doesn't exist: vertical-stack-in-card.
Even with saving the .js in raw mode and empty browser cache I cannot use the card. Seems to be a common problem?
https://community.home-assistant.io/t/custom-element-doesnt-exist-vertical-stack-in-card/309707/8

### LINKED ISSUE #153: Vertical Stack in card is down
Vertical Stack in card is down after last HA 2023.7.1 update!!

please know that frontend is down and not working properly 

our request to post new update version to fantastical card
/
Best regards

### PR DESCRIPTION
**Pull request by caseyjhol**
Fixes #146. Tested and confirmed as working in HA 2024.2.2.

Edit: looks like there's an issue when editing an existing card.

### CODE REVIEW

**Comment by BBESINET** [comment]
I go around this annoying issue by doing the following sequence:
- close the stackin-card I try to edit
- create a new card
- choose native grid or vertical  or horizontal card => the graphic interfaces pop up
- close this card (no need to save)
- open again my initial stack-in card "et voilà..."

Might-it help to find a way to fix the issue?

**Comment by ofekashery** [comment]
@caseyjhol Thank you ❤️ That's an awesome workaround.
Can you share more about the issue when editing an existing card? I couldn't reproduce it

**Comment by Bambouzle** [comment]
If I try to edit a custom vertical stack I get this:
first
If I create or edit a std vertical stack then edit the custom I get this :
second

This has to be done every time I refresh the page. The issue appends on Firefox, Chrome and HA Android App.

**Comment by ofekashery** [comment]
@Bambouzle thanks for the details, I'll look at this.

Can you mention your HA and browse versions please?

**Comment by Bambouzle** [comment]
This problem has happened to me for quite a while. Also I can't access custom stack when adding a card. To create a new custom stack I copy an existing one.

url for loading it into the interface: "/hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js?hacstag=142051833044"
(I tried adding "/local/vertical-stack-in-card.js?v=0.4.4" but no difference)

ha versions:
  Core 2024.8.3
  (and after updating Core  2024.9.3)
  Supervisor 2024.09.1
  Operating System 13.1
  Interface utilisateur 20240809.0

I also tried getting back to my oldest full save dating back january 23, 2024 and got the same result.
  Core 2024.1.6
  Supervisor 2024.09.1
  Operating System 13.1
  Interface utilisateur 20240104.0

custom Vertical stack version : 0.4.4
Browsers:
  Firefox: 130.0.1 (64 bits)
  Chrome: 129.0.6668.60 (Build officiel) (64 bits)
  Home Assistant Android App: 2024.7.3-full

**Comment by Bambouzle** [comment]
@ofekashery If I try to edit a custom card prior to anything I get this error message:


Using the same workaround as before or creating a new custom card mitigate this issue.

But I can now create a custom card through ui and the editing ui loads just fine through this path.

**Pull request merged**
