### PR TITLE
Add UI editor

### PR DESCRIPTION
**Pull request by sdrapha**
Add ui-editor by importing the native HA existing editor for vertical and horizontal cards

### CODE REVIEW

**Comment by ThomDietrich** [comment]
How does this one relate to #125 ?

**Comment by sdrapha** [comment]
> How does this one relate to #125 ?

Different aproach, #125 rewrites A LOT of stuff, from scratch, it's even hard to review all that code. (Althought it seems that implements extra new features, which is cool, but I never tested)

This one just pigbacks the already native UI editor from the native Vertical Stack card
It's a one line addition in the code, that works!! I've been using it now for months already, so much better to edit cards now...

**Comment by ThomDietrich** [comment]
Sounds great. Maybe additional features in #125 can be implemented after your PR was merged.

@ofekashery what's blocking this PR?

**Comment by ofekashery** [comment]
Thanks, @sdrapha!

**Pull request merged**
